# Generated by Django 5.0.7 on 2024-08-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('date', models.DateTimeField()),
                ('source', models.CharField(max_length=225)),
                ('article_link', models.URLField()),
                ('img_url', models.URLField()),
                ('content', models.TextField()),
                ('summary', models.TextField()),
            ],
        ),
    ]
