# Generated by Django 5.0.7 on 2024-08-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='media',
            field=models.URLField(default='null'),
            preserve_default=False,
        ),
    ]
