# Generated by Django 5.0.7 on 2024-08-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='img_url',
            new_name='top_image',
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
