# Generated by Django 5.2.5 on 2025-09-10 22:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=225, unique=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("source", models.CharField(max_length=225)),
                ("article_link", models.URLField()),
                ("top_image", models.URLField()),
                ("media", models.URLField()),
                ("content", models.TextField()),
                ("summary", models.TextField()),
                ("category", models.CharField(max_length=20)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["category", "-date"],
                        name="articles_ar_categor_b1bc18_idx",
                    ),
                    models.Index(fields=["-date"], name="articles_ar_date_fe9a8c_idx"),
                    models.Index(fields=["title"], name="articles_ar_title_ee81af_idx"),
                ],
                "unique_together": {("title", "article_link")},
            },
        ),
    ]
