# Generated by Django 5.0.7 on 2024-08-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='null', max_length=60),
            preserve_default=False,
        ),
    ]
