# Generated by Django 5.0.7 on 2024-08-09 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
