# Generated by Django 5.0.7 on 2024-09-09 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_images'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('title', 'article_link')},
        ),
    ]
